# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/nerglite/TEMPORARY FOLDER HERE/jarkom/project-1-pembenci-motor-matic"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/nerglite/TEMPORARY FOLDER HERE/jarkom/project-1-pembenci-motor-matic"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/nerglite/TEMPORARY FOLDER HERE/jarkom/project-1-pembenci-motor-matic/CMakeFiles" "/home/nerglite/TEMPORARY FOLDER HERE/jarkom/project-1-pembenci-motor-matic//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/nerglite/TEMPORARY FOLDER HERE/jarkom/project-1-pembenci-motor-matic/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named node

# Build rule for target.
node: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 node
.PHONY : node

# fast build rule for target.
node/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/build
.PHONY : node/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/main.cpp.s
.PHONY : main.cpp.s

node.o: node.cpp.o
.PHONY : node.o

# target to build an object file
node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/node.cpp.o
.PHONY : node.cpp.o

node.i: node.cpp.i
.PHONY : node.i

# target to preprocess a source file
node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/node.cpp.i
.PHONY : node.cpp.i

node.s: node.cpp.s
.PHONY : node.s

# target to generate assembly for a file
node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/node.cpp.s
.PHONY : node.cpp.s

segment.o: segment.cpp.o
.PHONY : segment.o

# target to build an object file
segment.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/segment.cpp.o
.PHONY : segment.cpp.o

segment.i: segment.cpp.i
.PHONY : segment.i

# target to preprocess a source file
segment.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/segment.cpp.i
.PHONY : segment.cpp.i

segment.s: segment.cpp.s
.PHONY : segment.s

# target to generate assembly for a file
segment.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/segment.cpp.s
.PHONY : segment.cpp.s

segment_handler.o: segment_handler.cpp.o
.PHONY : segment_handler.o

# target to build an object file
segment_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/segment_handler.cpp.o
.PHONY : segment_handler.cpp.o

segment_handler.i: segment_handler.cpp.i
.PHONY : segment_handler.i

# target to preprocess a source file
segment_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/segment_handler.cpp.i
.PHONY : segment_handler.cpp.i

segment_handler.s: segment_handler.cpp.s
.PHONY : segment_handler.s

# target to generate assembly for a file
segment_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/segment_handler.cpp.s
.PHONY : segment_handler.cpp.s

socket.o: socket.cpp.o
.PHONY : socket.o

# target to build an object file
socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/socket.cpp.o
.PHONY : socket.cpp.o

socket.i: socket.cpp.i
.PHONY : socket.i

# target to preprocess a source file
socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/socket.cpp.i
.PHONY : socket.cpp.i

socket.s: socket.cpp.s
.PHONY : socket.s

# target to generate assembly for a file
socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/socket.cpp.s
.PHONY : socket.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... node"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... node.o"
	@echo "... node.i"
	@echo "... node.s"
	@echo "... segment.o"
	@echo "... segment.i"
	@echo "... segment.s"
	@echo "... segment_handler.o"
	@echo "... segment_handler.i"
	@echo "... segment_handler.s"
	@echo "... socket.o"
	@echo "... socket.i"
	@echo "... socket.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

